// Generated by CoffeeScript 1.6.3
(function() {
  var exec, fs;

  exec = require('child_process').exec;

  fs = require('fs');

  module.exports = function(path, callback) {
    var args;
    args = "-t -s 1024 -o . " + path;
    return exec("qlmanage " + args, function(err, stdout) {
      var preview;
      preview = "" + path + ".png";
      return fs.exists(preview, function(exists) {
        return callback(exists ? preview : void 0);
      });
    });
  };

}).call(this);
