// Generated by CoffeeScript 1.7.1
(function() {
  var exec, fs, path, previewFile, temp;

  temp = require('temp');

  path = require('path');

  fs = require('fs');

  exec = require('child_process').exec;

  module.exports.previewFile = previewFile = function(inputPath, callback) {
    var args, command;
    args = "-t -s 1024 -o " + (path.dirname(inputPath)) + " " + inputPath;
    command = "qlmanage " + args;
    return exec(command, function(err, stdout) {
      var message, outputPath;
      if (err) {
        return callback(err);
      }
      outputPath = "" + inputPath + ".png";
      if (message = (stdout.match(/^\[ERROR\].*$/m) || [])[0]) {
        return callback(new Error(message));
      }
      return callback(err, outputPath);
    });
  };

  module.exports.preview = function(buffer, extname, callback) {
    temp.track();
    return temp.mkdir("quicklook", function(err, dirPath) {
      var inputPath;
      if (err) {
        return callback(err);
      }
      inputPath = path.join(dirPath, "file" + extname);
      return fs.writeFile(inputPath, buffer, function(err) {
        if (err) {
          return callback(err);
        }
        return previewFile(inputPath, function(err, outputPath) {
          if (err) {
            return callback(err);
          }
          return fs.readFile(outputPath, function(err, data) {
            if (err) {
              return callback(err);
            }
            return callback(err, data);
          });
        });
      });
    });
  };

}).call(this);
